services:
  golang:
    entrypoint:
      - /usr/local/go/bin/go
      - run
      - /hashbrowns/go/hashbrowns.go
    environment:
      GOPATH: /hashbrowns/go
    image: golang:1.25
    init: true
    volumes:
      - ./:/hashbrowns
    working_dir: /hashbrowns/go

  python:
    entrypoint:
      - /usr/local/bin/python
      - /hashbrowns/python/hashbrowns.py
    image: python:3.13.7-slim
    init: true
    volumes:
      - ./:/hashbrowns
    working_dir: /hashbrowns/python
